### PR TITLE
Update OFD.hsc

### PR DESCRIPTION
**Pull request by angerman**
Make it cross compile!

### CODE REVIEW

**Comment by phadej** [comment]
Doesn’t TOOL_MIN_VERSION_hsc2hs work?

**Comment by angerman** [comment]
@phadej for
```
#if !TOOL_MIN_VERSION_hsc2hs(0,68,7)
...
#endif
```
I get `error: missing binary operator before token "("` 🤷‍♂️

**Comment by phadej** [comment]
Sorry I didn't doublecheck, it is MIN_TOOL_...

```

``cabal-version: 1.20``
-----------------------

* Add support for new :pkg-field:`license-files` field for declaring
  multiple license documents.

* New CPP Macro ``MIN_TOOL_VERSION_$buildtool``.

```

**Comment by bgamari** [comment]
I fixed this same issue in #21.

**Pull request closed without merging**
